title = "Hakeem Almidan"
baseURL = "http://hakeem-almidan.com/"
theme = "zen"
languageCode = "en-GB"
defaultContentLanguage = "en"
pluralizelisttitles = false
removePathAccents = true
paginate = 10
paginatePath = "page"
rssLimit = 20

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "JSON", "SearchIndex" ]
section = [ "HTML", "RSS", "JSON" ]

[params]
contact = "hakeemmidan@gmail.com"
googleAnalytics = "UA-162259002-1"
copyright = "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
description = "The zen theme for Hugo example site."
dateformat = "2 January, 2006"
feedlinks = true
favicon = "apple-touch-icon.png"
icon = "apple-touch-icon.png"
image = "apple-touch-icon.png"
imageMaxWidth = 400
poweredby = false
sidebar = true

